packages:
  - 'packages/*'
  - 'services/*'

minimumReleaseAge: 1440

catalog:
  # deps
  typescript: ^5.9.3
  tsx: ^4.21.0
  # dev deps
  '@types/node': ^24
  pino-pretty: ^13.1.3
  # test deps
  vitest: ^4.0.18
  vite-tsconfig-paths: ^6.0.5
  '@vitest/coverage-v8': ^4.0.18
